image: atlassian/default-image:latest

pipelines:
  branches:
    staging: # Trigger when code is pushed to `staging`
      - step:
          name: Deploy to WP Engine Staging
          script:
            - echo "Starting deployment to WP Engine STG"
            - ssh-keyscan git.wpengine.com >> ~/.ssh/known_hosts
            - git push --force git@git.wpengine.com:rishumitstg.git staging:master